//@ pragma UseQApplication
// Keybindings cheat-sheet — Quickshell. Replaces scripts/keybindings/keybindings.sh
// (rofi). Big window: app tabs on the left, that app's keybindings on the right.
// Bound to Mod+Shift+Slash. Resident daemon, toggled over IPC.
//
// Data + extraction live in scripts/quickshell/kbctl.sh:
//   refresh -> re-run the per-app extractors (correct config paths)
//   list    -> JSON [{app, count, bindings:[{key,desc}]}]
// Enter copies the highlighted "key  desc" to the clipboard.
import Quickshell
import Quickshell.Wayland
import Quickshell.Io
import QtQuick
import common
import QtQuick.Controls
import QtQuick.Layouts

ShellRoot {
    id: root
    readonly property string kbctl: Quickshell.env("HOME") + "/.dotfiles/scripts/quickshell/kbctl.sh"

    // Palette: common/Colors.qml, generated by scripts/theme.sh.
    readonly property color bg:      Colors.bg
    readonly property color inputBg: Colors.inputBg
    readonly property color outline: Colors.outline
    readonly property color accent:  Colors.accent
    readonly property color selBg:   Colors.selBg
    readonly property color fg:      Colors.fg
    readonly property color subtext: Colors.subtext
    readonly property string uiFont: "JetBrainsMono Nerd Font"

    property var apps: []          // [{app,count,bindings:[{key,desc}]}]
    property int curApp: 0

    // ── process plumbing ──────────────────────────────────────────────────
    Process {
        id: lister
        command: ["bash", kbctl, "list"]
        stdout: StdioCollector { onStreamFinished: {
            try { var a = JSON.parse(text); if (a.length) { apps = a; if (curApp >= a.length) curApp = 0; } }
            catch (e) {}
        } }
    }
    Process {
        id: refresher
        command: ["bash", kbctl, "refresh"]
        stdout: StdioCollector { onStreamFinished: lister.running = true }
    }
    function loadFast() { lister.running = true; }
    function refresh()  { refresher.running = true; }        // chains to list on finish
    Process { id: copier }
    function copyLine(s) { copier.command = ["bash", "-c", "printf %s " + JSON.stringify(s) + " | wl-copy"]; copier.running = true; }

    IpcHandler {
        target: "kb"
        function toggle(): void {
            if (win.shown) { win.shown = false; return; }
            curApp = 0; search.text = "";        // reset to first app tab + clear filter
            loadFast(); refresh(); win.shown = true;
        }
    }
    Component.onCompleted: refresh()   // prime at daemon boot

    readonly property var curBindings: (apps.length && apps[curApp]) ? apps[curApp].bindings : []

    PanelWindow {
        id: win
        // `shown` is what callers set. The window stays mapped until the close
        // animation has run out, which is what `visible` tracks.
        property bool shown: false
        visible: shown || anim > 0
        // ponytail: no resident daemon; quit once hidden and idle (Qt.quit kills running Processes)
        onVisibleChanged: if (!visible) quitter.start()
        Timer { id: quitter; interval: 200; repeat: true; onTriggered: if (win.visible) stop(); else if (!(lister.running || refresher.running || copier.running)) Qt.quit() }
        anchors { top: false; bottom: false; left: false; right: false }
        implicitWidth: 1240
        implicitHeight: 820
        color: "transparent"
        WlrLayershell.layer: WlrLayer.Overlay
        WlrLayershell.keyboardFocus: shown ? WlrKeyboardFocus.Exclusive : WlrKeyboardFocus.None
        WlrLayershell.namespace: "quickshell-keybindings"

        // Expand from the centre on open, collapse back on close.
        property real anim: shown ? 1 : 0
        // Opening rides caelestia's expressive fast-spatial curve, which overshoots a
        // touch and settles. Closing rides the effects curve instead: it is quicker and
        // does not overshoot, because a panel that bounces on its way out reads as a
        // glitch. Anim.DefaultSpatial (500ms) is what upstream's launcher uses for the
        // open; that felt slow for menus opened this often.
        Behavior on anim { Anim { type: win.shown ? Anim.FastSpatial : Anim.FastEffects } }
        onShownChanged: { if (shown) Qt.callLater(function () { search.forceActiveFocus(); }) }

        Rectangle {
            anchors.fill: parent
            transform: Scale { origin.y: win.height / 2; yScale: win.anim }
            // Fade alongside the scale, as caelestia's panels do. Clamped because the
            // spatial curve overshoots past 1 on the way in.
            opacity: Math.min(1, win.anim)
            radius: 4
            color: bg
            border.color: outline
            border.width: 1

            // ═══ LEFT: app tabs (fixed-width anchored pane) ═════════════════
            ColumnLayout {
                id: leftPane
                anchors { left: parent.left; top: parent.top; bottom: parent.bottom; margins: 16 }
                width: 240
                spacing: 4
                Text { text: "󰌌  Keybindings"; color: accent; font.family: uiFont; font.pixelSize: 18; font.bold: true; Layout.bottomMargin: 8 }
                Repeater {
                    model: apps
                    delegate: StyledRect {
                        required property int index
                        required property var modelData
                        Layout.fillWidth: true; implicitHeight: 46; radius: 0
                        color: index === curApp ? selBg : "transparent"
                        RowLayout {
                            anchors.fill: parent; anchors.leftMargin: 12; anchors.rightMargin: 12
                            Text { text: modelData.app; color: fg; font.family: uiFont; font.pixelSize: 16; Layout.fillWidth: true }
                            Text { text: modelData.count; color: index === curApp ? fg : subtext; font.family: uiFont; font.pixelSize: 13 }
                        }
                        StateLayer {
                            onClicked: { curApp = index; search.text = ""; search.forceActiveFocus(); } }
                    }
                }
                Item { Layout.fillHeight: true }
                Text { text: "Tab / Shift+Tab switch\nEnter copy · Esc close"; color: subtext; font.family: uiFont; font.pixelSize: 11; Layout.fillWidth: true }
            }

            Rectangle { anchors { left: leftPane.right; leftMargin: 12; top: parent.top; bottom: parent.bottom; topMargin: 16; bottomMargin: 16 }
                        width: 1; color: outline }

            // ═══ RIGHT: search + bindings (anchored, fills remaining width) ══
            ColumnLayout {
                anchors { left: leftPane.right; leftMargin: 25; right: parent.right; top: parent.top; bottom: parent.bottom
                          rightMargin: 16; topMargin: 16; bottomMargin: 16 }
                spacing: 10

                    Rectangle {
                        Layout.fillWidth: true; implicitHeight: 48; radius: 0
                        color: inputBg; border.color: accent; border.width: 1
                        RowLayout {
                            anchors.fill: parent; anchors.leftMargin: 12; anchors.rightMargin: 12; spacing: 10
                            Text { text: ""; color: accent; font.family: uiFont; font.pixelSize: 17 }
                            StyledTextField {
                                id: search
                                Layout.fillWidth: true; focus: true
                                color: fg; font.family: uiFont; font.pixelSize: 16; background: null
                                placeholderText: (apps.length ? apps[curApp].app : "") + " — filter keys or actions…"
                                placeholderTextColor: subtext
                                onTextChanged: kbList.currentIndex = 0
                                Keys.onPressed: (e) => {
                                    if (e.key === Qt.Key_Escape) { win.shown = false; e.accepted = true; }
                                    else if (e.key === Qt.Key_Down) { kbList.incrementCurrentIndex(); e.accepted = true; }
                                    else if (e.key === Qt.Key_Up)   { kbList.decrementCurrentIndex(); e.accepted = true; }
                                    else if (e.key === Qt.Key_Backtab || (e.key === Qt.Key_Tab && (e.modifiers & Qt.ShiftModifier))) {
                                        if (apps.length) { curApp = (curApp - 1 + apps.length) % apps.length; search.text = ""; } e.accepted = true;
                                    } else if (e.key === Qt.Key_Tab) {
                                        if (apps.length) { curApp = (curApp + 1) % apps.length; search.text = ""; } e.accepted = true;
                                    } else if (e.key === Qt.Key_Return || e.key === Qt.Key_Enter) {
                                        var m = kbList.currentItem ? kbList.currentItem.rowData : null;
                                        if (m) copyLine(m.key + "  " + m.desc);
                                        e.accepted = true;
                                    }
                                }
                            }
                            Text { text: kbList.count + ""; color: subtext; font.family: uiFont; font.pixelSize: 13 }
                        }
                    }

                    ListView {
                        id: kbList
                        Layout.fillWidth: true; Layout.fillHeight: true; clip: true
                        boundsBehavior: Flickable.StopAtBounds
                        ScrollBar.vertical: StyledScrollBar { flickable: kbList }
                        model: {
                            var qy = search.text.toLowerCase();
                            var out = [];
                            for (var i = 0; i < curBindings.length; i++) {
                                var b = curBindings[i];
                                if (qy === "" || (b.key + " " + b.desc).toLowerCase().indexOf(qy) !== -1) out.push(b);
                            }
                            return out;
                        }
                        onCurrentIndexChanged: positionViewAtIndex(currentIndex, ListView.Contain)
                        delegate: StyledRect {
                            required property int index
                            required property var modelData
                            property var rowData: modelData
                            width: ListView.view.width; height: 38; radius: 0
                            color: index === kbList.currentIndex ? selBg : (index % 2 ? Colors.zebra : "transparent")
                            RowLayout {
                                anchors.fill: parent; anchors.leftMargin: 12; anchors.rightMargin: 12; spacing: 16
                                Text { text: modelData.key; color: index === kbList.currentIndex ? fg : accent; font.family: uiFont; font.pixelSize: 14
                                       Layout.preferredWidth: 260; elide: Text.ElideRight }
                                Text { text: modelData.desc; color: fg; font.family: uiFont; font.pixelSize: 14
                                       Layout.fillWidth: true; elide: Text.ElideRight }
                            }
                            StateLayer {
                                onEntered: kbList.currentIndex = index
                                onClicked: copyLine(modelData.key + "  " + modelData.desc) }
                        }
                    }
                }
            }
        }
    }
