-- Tokyo Night — generated by scripts/theme.sh. Do not edit.
-- Same colours as niri's focus ring (modules/colors.kdl).
hl.config({
    general = {
        col = {
            active_border   = { colors = { "rgb(bb9af7)", "rgb(7dcfff)" }, angle = 225 },
            inactive_border = "rgb(292e42)",
        },
    },
})
