-- ═══════════════════════════════════════════════════════════════════════════
-- HYPRLAND CONFIG — ROOT
-- Port of ~/.config/niri. Scrolling layout, same binds (binds.lua).
-- colors.lua is generated by scripts/theme.sh; do not edit it by hand.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Outputs ────────────────────────────────────────────────────────────────
hl.monitor({ output = "eDP-1", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

-- ── Environment (niri modules/environment.kdl) ──────────────────────────────
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "xdgdesktopportal")
hl.env("QML2_IMPORT_PATH", "/home/nova/.config/quickshell")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "25")

-- ── Look ───────────────────────────────────────────────────────────────────
hl.config({
    general = {
        layout      = "scrolling",
        gaps_in     = 5,   -- niri `gaps 10` is the full gap between windows
        gaps_out    = 10,
        border_size = 2,   -- stands in for niri's focus ring
        resize_on_border = true,
    },
    decoration = {
        rounding = 0,
        shadow   = { enabled = false },
        blur     = { enabled = true, size = 3, passes = 4, noise = 0.0, vibrancy = 0.0 },
    },
    scrolling = {
        column_width             = 0.75,              -- niri window-rule default
        explicit_column_widths   = "0.5, 0.75, 0.333", -- niri preset-column-widths
        fullscreen_on_one_column = false,
        focus_fit_method         = 1,                 -- fit, like niri (no centering)
        follow_focus             = true,
        wrap_focus               = false,             -- niri stops at the ends
        wrap_swapcol             = false,
    },
    input = {
        kb_layout    = "us",
        follow_mouse = 1,   -- focus-follows-mouse
        sensitivity  = 0,
        touchpad = {
            tap_to_click         = true,
            disable_while_typing = true,
            natural_scroll       = true,
        },
    },
    cursor = {
        hide_on_key_press        = true,
        warp_on_change_workspace = 1,
    },
    binds = {
        scroll_event_delay = 150,   -- niri cooldown-ms=150 on wheel binds
    },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
        disable_splash_rendering = true,
        focus_on_activate       = true,
    },
    ecosystem = {
        no_update_news    = true,
        no_donation_nag   = true,
    },
})

-- ── Animations (approximations of niri modules/layout.kdl) ───────────────────
-- Material 3 "spatial fast" overshoot curve used by niri window-open.
hl.curve("m3SpatialFast", { type = "bezier", points = { {0.42, 1.67}, {0.21, 0.9} } })
hl.curve("m3EffectsFast", { type = "bezier", points = { {0.31, 0.94}, {0.34, 1} } })
-- niri springs: damping-ratio 1.0 = no bounce, 0.75 = light bounce.
hl.curve("move",      { type = "spring", mass = 1, stiffness = 450, dampening = 42 })
hl.curve("wsBounce",  { type = "spring", mass = 1, stiffness = 800, dampening = 42 })

hl.animation({ leaf = "windowsIn",   enabled = true, speed = 3.5, bezier = "m3SpatialFast", style = "slide right" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 1.5, bezier = "m3EffectsFast", style = "slide right" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4,   spring = "move" })
hl.animation({ leaf = "fadeIn",      enabled = true, speed = 3.5, bezier = "m3EffectsFast" })
hl.animation({ leaf = "fadeOut",     enabled = true, speed = 1.5, bezier = "m3EffectsFast" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 4,   spring = "wsBounce", style = "slidevert" })
hl.animation({ leaf = "layers",      enabled = true, speed = 3,   bezier = "m3EffectsFast", style = "fade" })

-- ── Workspaces: niri `workspace "Main"` / `workspace "Work"` ─────────────────
hl.workspace_rule({ workspace = "1", default_name = "Main", persistent = true, default = true })
hl.workspace_rule({ workspace = "2", default_name = "Work", persistent = true })

-- ── Window rules (niri modules/window-rules.kdl) ────────────────────────────
hl.window_rule({ match = { class = "^scrcpy$" },              scrolling_width = 0.3, workspace = "1" })
hl.window_rule({ match = { title = "^dexmode$" },             maximize = true,       workspace = "1" })
hl.window_rule({ match = { class = "^lin-whatsapp$" },        workspace = "1" })
hl.window_rule({ match = { class = "^zen$" },                 workspace = "1" })
hl.window_rule({ match = { class = "^com.mitchellh.ghostty$" }, workspace = "2" })
hl.window_rule({ match = { title = "^tmux$" },                scrolling_width = 1.0 })
hl.window_rule({ match = { title = "^tasks-scratchpad$" },    float = true, size = {1200, 850}, center = true })
hl.window_rule({ match = { class = "^satty$" },               float = true })
hl.window_rule({ match = { title = "^Select File to Attach$" }, float = true })
hl.window_rule({ match = { class = "^zenity$" },              float = true })
hl.window_rule({ match = { class = "^labwc$" },               maximize = true })
hl.window_rule({ match = { class = "^com.danklinux.dms$" },   float = true })

-- ── Startup (niri modules/startup.kdl) ──────────────────────────────────────
hl.on("hyprland.start", function()
    -- DMS, Emacs and the notification daemon hang off graphical-session.target.
    -- Hand systemd this session's env, bring the target up through
    -- hyprland-session.target, then start DMS (niri pulls it via niri.service.wants).
    -- Once DMS answers, hide its bar (the island replaces it here; niri's
    -- startup.kdl reveals it again), turn off DMS's volume/brightness OSD (the
    -- island shows its own; niri turns DMS's back on) and start the island.
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_QPA_PLATFORM QT_QPA_PLATFORMTHEME QML2_IMPORT_PATH XCURSOR_THEME XCURSOR_SIZE"
        .. " && systemctl --user start hyprland-session.target"
        -- restart, not start: if DMS is still alive from an older session it
        -- would stay drawing on that compositor (no wallpaper/bar here).
        .. " && systemctl --user restart quickshell-notifications.service dms.service"
        .. "; for i in $(seq 50); do dms ipc call bar hide id default 2>/dev/null | grep -q SUCCESS && break; sleep 0.2; done"
        .. "; dms ipc call settings set osdVolumeEnabled false; dms ipc call settings set osdBrightnessEnabled false"
        .. "; qs -c island -d")
    hl.exec_cmd("swayidle")
    hl.exec_cmd("kdeconnectd")
    hl.exec_cmd("udiskie --no-tray --notify")
    hl.exec_cmd("sshfs nova@novahome:/home/nova /home/nova/server -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3")
end)

-- Leave no Hyprland socket behind for a later niri session's DMS to latch onto.
hl.on("hyprland.shutdown", function()
    hl.exec_cmd("systemctl --user stop hyprland-session.target; systemctl --user unset-environment HYPRLAND_INSTANCE_SIGNATURE")
end)

require("colors")
require("binds")
