//@ pragma UseQApplication
// Window switcher — Quickshell. Replaces scripts/rofi/windows.sh. Bound to Mod+Tab.
// Uses the Wayland foreign-toplevel list (no external process). Single-column
// list: app icon + title + app_id. Enter/click focuses (toplevel.activate()).
// (niri has no per-window screencopy, so no live preview — list only.)
import Quickshell
import Quickshell.Wayland
import Quickshell.Io
import QtQuick
import common
import QtQuick.Controls
import QtQuick.Layouts

ShellRoot {
    id: root

    // Palette: common/Colors.qml, generated by scripts/theme.sh.
    readonly property color bg:      Colors.bg
    readonly property color inputBg: Colors.inputBg
    readonly property color outline: Colors.outline
    readonly property color accent:  Colors.accent
    readonly property color selBg:   Colors.selBg
    readonly property color fg:      Colors.fg
    readonly property color subtext: Colors.subtext
    readonly property string uiFont: "JetBrainsMono Nerd Font"

    property int sel: 0
    property string filter: ""

    readonly property var rows: {
        var all = ToplevelManager.toplevels.values;
        var qy = filter.toLowerCase();
        var out = [];
        for (var i = 0; i < all.length; i++) {
            var t = all[i];
            if (qy === "" || ((t.title || "") + " " + (t.appId || "")).toLowerCase().indexOf(qy) !== -1) out.push(t);
        }
        return out;
    }
    function activate(t) { if (t) t.activate(); win.shown = false; }

    IpcHandler {
        target: "switcher"
        function toggle(): void {
            if (win.shown) { win.shown = false; return; }
            search.text = "";                               // clear stale filter text (onTextChanged resets filter+sel)
            sel = (rows.length > 1 ? 1 : 0);                // preselect previous window
            win.shown = true;
        }
    }

    PanelWindow {
        id: win
        // `shown` is what callers set. The window stays mapped until the close
        // animation has run out, which is what `visible` tracks.
        property bool shown: false
        visible: shown || anim > 0
        anchors { top: false; bottom: false; left: false; right: false }
        implicitWidth: 760
        readonly property int maxH: 600
        implicitHeight: Math.min(maxH, 92 + Math.max(1, list.count) * 54)
        color: "transparent"
        WlrLayershell.layer: WlrLayer.Overlay
        WlrLayershell.keyboardFocus: shown ? WlrKeyboardFocus.Exclusive : WlrKeyboardFocus.None
        WlrLayershell.namespace: "quickshell-switcher"

        // Expand from the centre on open, collapse back on close.
        property real anim: shown ? 1 : 0
        // Opening rides caelestia's expressive fast-spatial curve, which overshoots a
        // touch and settles. Closing rides the effects curve instead: it is quicker and
        // does not overshoot, because a panel that bounces on its way out reads as a
        // glitch. Anim.DefaultSpatial (500ms) is what upstream's launcher uses for the
        // open; that felt slow for menus opened this often.
        Behavior on anim { Anim { type: win.shown ? Anim.FastSpatial : Anim.FastEffects } }
        onShownChanged: { if (shown) Qt.callLater(function () { search.forceActiveFocus(); }) }

        Rectangle {
            anchors.fill: parent
            transform: Scale { origin.y: win.height / 2; yScale: win.anim }
            // Fade alongside the scale, as caelestia's panels do. Clamped because the
            // spatial curve overshoots past 1 on the way in.
            opacity: Math.min(1, win.anim)
            radius: 4
            color: bg
            border.color: outline
            border.width: 1

            ColumnLayout {
                anchors.fill: parent
                anchors.margins: 14
                spacing: 10

                Rectangle {
                    Layout.fillWidth: true; implicitHeight: 48; radius: 0
                    color: inputBg; border.color: accent; border.width: 1
                    RowLayout {
                        anchors.fill: parent; anchors.leftMargin: 14; anchors.rightMargin: 14; spacing: 10
                        Text { text: ""; color: accent; font.family: uiFont; font.pixelSize: 18 }
                        StyledTextField {
                            id: search
                            Layout.fillWidth: true; focus: true
                            color: fg; font.family: uiFont; font.pixelSize: 16; background: null
                            placeholderText: "Switch window…"
                            placeholderTextColor: subtext
                            onTextChanged: { filter = text; sel = 0; }
                            Keys.onPressed: (e) => {
                                if (e.key === Qt.Key_Escape) { win.shown = false; e.accepted = true; }
                                else if (e.key === Qt.Key_Down || (e.key === Qt.Key_Tab && !(e.modifiers & Qt.ShiftModifier))) {
                                    if (rows.length) sel = (sel + 1) % rows.length; e.accepted = true;
                                } else if (e.key === Qt.Key_Up || e.key === Qt.Key_Backtab || (e.key === Qt.Key_Tab && (e.modifiers & Qt.ShiftModifier))) {
                                    if (rows.length) sel = (sel - 1 + rows.length) % rows.length; e.accepted = true;
                                } else if (e.key === Qt.Key_Return || e.key === Qt.Key_Enter) {
                                    activate(rows.length ? rows[sel] : null); e.accepted = true;
                                }
                            }
                        }
                        Text { text: rows.length + ""; color: subtext; font.family: uiFont; font.pixelSize: 13 }
                    }
                }

                ListView {
                    id: list
                    Layout.fillWidth: true; Layout.fillHeight: true; clip: true
                    boundsBehavior: Flickable.StopAtBounds
                    ScrollBar.vertical: StyledScrollBar { flickable: list }
                    model: rows
                    currentIndex: sel
                    onCurrentIndexChanged: positionViewAtIndex(currentIndex, ListView.Contain)
                    delegate: StyledRect {
                        required property int index
                        required property var modelData
                        width: ListView.view.width; height: 54; radius: 0
                        color: index === sel ? selBg : "transparent"
                        RowLayout {
                            anchors.fill: parent; anchors.leftMargin: 14; anchors.rightMargin: 14; spacing: 14
                            Image {
                                Layout.preferredWidth: 30; Layout.preferredHeight: 30
                                source: Quickshell.iconPath(modelData.appId, "application-x-executable")
                                sourceSize.width: 30; sourceSize.height: 30; fillMode: Image.PreserveAspectFit
                            }
                            ColumnLayout {
                                Layout.fillWidth: true; spacing: 0
                                Text { text: modelData.title || "(untitled)"; color: fg; font.family: uiFont; font.pixelSize: 15
                                       elide: Text.ElideRight; Layout.fillWidth: true }
                                Text { text: modelData.appId || ""; color: index === sel ? fg : subtext; font.family: uiFont; font.pixelSize: 12
                                       elide: Text.ElideRight; Layout.fillWidth: true }
                            }
                        }
                        StateLayer {
                            onEntered: sel = index
                            onClicked: activate(modelData) }
                    }
                }
            }
        }
    }
}
