//@ pragma UseQApplication
// App launcher (drun) — Quickshell. Replaces `rofi -show drun -theme spotlight`.
// Bound to Mod+D. Resident daemon, toggled over IPC.
//
// scripts/quickshell/applaunch.sh: list (JSON, most-used first) / launch <file>.
// Icons resolve via Quickshell.iconPath(name). Enter or click launches + hides.
import Quickshell
import Quickshell.Wayland
import Quickshell.Io
import QtQuick
import common
import QtQuick.Controls
import QtQuick.Layouts

ShellRoot {
    id: root
    readonly property string applaunch: Quickshell.env("HOME") + "/.dotfiles/scripts/quickshell/applaunch.sh"

    // Palette: common/Colors.qml, generated by scripts/theme.sh.
    readonly property color bg:      Colors.bg
    readonly property color inputBg: Colors.inputBg
    readonly property color outline: Colors.outline
    readonly property color accent:  Colors.accent
    readonly property color selBg:   Colors.selBg
    readonly property color fg:      Colors.fg
    readonly property color subtext: Colors.subtext
    readonly property string uiFont: "JetBrainsMono Nerd Font"

    property var apps: []          // [{id,name,icon,file}]

    Process {
        id: lister
        command: ["bash", applaunch, "list"]
        stdout: StdioCollector { onStreamFinished: { try { apps = JSON.parse(text); } catch (e) { apps = []; } } }
    }
    Process { id: launcher }
    function reload() { lister.running = true; }
    function launch(file) {
        launcher.command = ["bash", applaunch, "launch", file];
        launcher.running = true;
        win.shown = false;
    }

    IpcHandler {
        target: "launcher"
        function toggle(): void {
            if (win.shown) { win.shown = false; return; }
            search.text = ""; reload(); win.shown = true;
        }
    }
    Component.onCompleted: reload()

    PanelWindow {
        id: win
        // `shown` is what callers set. The window stays mapped until the close
        // animation has run out, which is what `visible` tracks.
        property bool shown: false
        visible: shown || anim > 0
        // ponytail: no resident daemon; quit once hidden and idle (Qt.quit kills running Processes)
        onVisibleChanged: if (!visible) quitter.start()
        Timer { id: quitter; interval: 200; repeat: true; onTriggered: if (win.visible) stop(); else if (!(lister.running || launcher.running)) Qt.quit() }
        anchors { top: false; bottom: false; left: false; right: false }
        implicitWidth: 680
        readonly property int maxH: 560
        implicitHeight: Math.min(maxH, 104 + Math.max(1, appList.count) * 52)
        color: "transparent"
        WlrLayershell.layer: WlrLayer.Overlay
        WlrLayershell.keyboardFocus: shown ? WlrKeyboardFocus.Exclusive : WlrKeyboardFocus.None
        WlrLayershell.namespace: "quickshell-launcher"

        // Expand from the centre on open, collapse back on close.
        property real anim: shown ? 1 : 0
        // Opening rides caelestia's expressive fast-spatial curve, which overshoots a
        // touch and settles. Closing rides the effects curve instead: it is quicker and
        // does not overshoot, because a panel that bounces on its way out reads as a
        // glitch. Anim.DefaultSpatial (500ms) is what upstream's launcher uses for the
        // open; that felt slow for menus opened this often.
        Behavior on anim { Anim { type: win.shown ? Anim.FastSpatial : Anim.FastEffects } }
        onShownChanged: { if (shown) Qt.callLater(function () { search.forceActiveFocus(); }) }

        Rectangle {
            anchors.fill: parent
            transform: Scale { origin.y: win.height / 2; yScale: win.anim }
            // Fade alongside the scale, as caelestia's panels do. Clamped because the
            // spatial curve overshoots past 1 on the way in.
            opacity: Math.min(1, win.anim)
            radius: 4
            color: bg
            border.color: outline
            border.width: 1

            ColumnLayout {
                anchors.fill: parent
                anchors.margins: 14
                spacing: 10

                // search
                Rectangle {
                    Layout.fillWidth: true; implicitHeight: 50; radius: 0
                    color: inputBg; border.color: accent; border.width: 1
                    RowLayout {
                        anchors.fill: parent; anchors.leftMargin: 14; anchors.rightMargin: 14; spacing: 10
                        Text { text: ""; color: accent; font.family: uiFont; font.pixelSize: 20 }
                        StyledTextField {
                            id: search
                            Layout.fillWidth: true; focus: true
                            color: fg; font.family: uiFont; font.pixelSize: 17; background: null
                            placeholderText: "Search applications…"
                            placeholderTextColor: subtext
                            onTextChanged: appList.currentIndex = 0
                            Keys.onPressed: (e) => {
                                if (e.key === Qt.Key_Escape) { win.shown = false; e.accepted = true; }
                                else if (e.key === Qt.Key_Down) { appList.incrementCurrentIndex(); e.accepted = true; }
                                else if (e.key === Qt.Key_Up)   { appList.decrementCurrentIndex(); e.accepted = true; }
                                else if (e.key === Qt.Key_Return || e.key === Qt.Key_Enter) {
                                    var m = appList.currentItem ? appList.currentItem.rowData : null;
                                    if (m) launch(m.file);
                                    e.accepted = true;
                                }
                            }
                        }
                        Text { text: appList.count + ""; color: subtext; font.family: uiFont; font.pixelSize: 13 }
                    }
                }

                ListView {
                    id: appList
                    Layout.fillWidth: true; Layout.fillHeight: true; clip: true
                    boundsBehavior: Flickable.StopAtBounds
                    ScrollBar.vertical: StyledScrollBar { flickable: appList }
                    model: {
                        var qy = search.text.toLowerCase();
                        if (qy === "") return apps;
                        var out = [];
                        for (var i = 0; i < apps.length; i++)
                            if (apps[i].name.toLowerCase().indexOf(qy) !== -1) out.push(apps[i]);
                        return out;
                    }
                    onCurrentIndexChanged: positionViewAtIndex(currentIndex, ListView.Contain)
                    delegate: StyledRect {
                        required property int index
                        required property var modelData
                        property var rowData: modelData
                        width: ListView.view.width; height: 52; radius: 0
                        color: index === appList.currentIndex ? selBg : "transparent"
                        RowLayout {
                            anchors.fill: parent; anchors.leftMargin: 12; anchors.rightMargin: 12; spacing: 14
                            Image {
                                Layout.preferredWidth: 32; Layout.preferredHeight: 32
                                source: Quickshell.iconPath(modelData.icon, "application-x-executable")
                                sourceSize.width: 32; sourceSize.height: 32
                                fillMode: Image.PreserveAspectFit
                            }
                            Text { text: modelData.name; color: fg; font.family: uiFont; font.pixelSize: 16
                                   Layout.fillWidth: true; elide: Text.ElideRight }
                        }
                        StateLayer {
                            onEntered: appList.currentIndex = index
                            onClicked: launch(modelData.file) }
                    }
                }
            }
        }
    }
}
