// ${THEME_LABEL} — generated by scripts/theme.sh. Do not edit.
// Singleton imported by every menu daemon: `import "../common"` then Colors.bg.
pragma Singleton
import Quickshell
import QtQuick

Singleton {
    readonly property string themeName: "${THEME_NAME}"

    // Roles the menus actually use. The alpha prefixes keep the translucent
    // look the hand-written palettes had: e6 on the panel, d0 on input fields.
    readonly property color bg:      "#e6${BASE}"
    readonly property color inputBg: "#d0${SURFACE0}"
    readonly property color outline: "#${SURFACE1}"
    readonly property color accent:  "#${ACCENT}"
    readonly property color selBg:   "#${SURFACE1}"
    readonly property color fg:      "#${TEXT}"
    readonly property color subtext: "#${OVERLAY1}"
    // 8% text, for alternating list rows.
    readonly property color zebra:   "#14${TEXT}"

    // Full palette, for menus that need more than the seven roles above.
    readonly property color crust:    "#${CRUST}"
    readonly property color mantle:   "#${MANTLE}"
    readonly property color base:     "#${BASE}"
    readonly property color surface0: "#${SURFACE0}"
    readonly property color surface1: "#${SURFACE1}"
    readonly property color surface2: "#${SURFACE2}"
    readonly property color overlay0: "#${OVERLAY0}"
    readonly property color overlay1: "#${OVERLAY1}"
    readonly property color overlay2: "#${OVERLAY2}"
    readonly property color subtext0: "#${SUBTEXT0}"
    readonly property color subtext1: "#${SUBTEXT1}"
    readonly property color text:     "#${TEXT}"
    readonly property color red:      "#${RED}"
    readonly property color maroon:   "#${MAROON}"
    readonly property color peach:    "#${PEACH}"
    readonly property color yellow:   "#${YELLOW}"
    readonly property color green:    "#${GREEN}"
    readonly property color teal:     "#${TEAL}"
    readonly property color sky:      "#${SKY}"
    readonly property color sapphire: "#${SAPPHIRE}"
    readonly property color blue:     "#${BLUE}"
    readonly property color lavender: "#${LAVENDER}"
    readonly property color mauve:    "#${MAUVE}"
    readonly property color pink:     "#${PINK}"
}
