// Tokyo Night — generated by scripts/theme.sh. Do not edit.
// Singleton imported by every menu daemon: `import "../common"` then Colors.bg.
pragma Singleton
import Quickshell
import QtQuick

Singleton {
    readonly property string themeName: "tokyonight"

    // Roles the menus actually use. The alpha prefixes keep the translucent
    // look the hand-written palettes had: e6 on the panel, d0 on input fields.
    readonly property color bg:      "#e61a1b26"
    readonly property color inputBg: "#d024283b"
    readonly property color outline: "#292e42"
    readonly property color accent:  "#bb9af7"
    readonly property color selBg:   "#292e42"
    readonly property color fg:      "#c0caf5"
    readonly property color subtext: "#565f89"
    // 8% text, for alternating list rows.
    readonly property color zebra:   "#14c0caf5"

    // Full palette, for menus that need more than the seven roles above.
    readonly property color crust:    "#0c0e14"
    readonly property color mantle:   "#16161e"
    readonly property color base:     "#1a1b26"
    readonly property color surface0: "#24283b"
    readonly property color surface1: "#292e42"
    readonly property color surface2: "#3b4261"
    readonly property color overlay0: "#414868"
    readonly property color overlay1: "#565f89"
    readonly property color overlay2: "#737aa2"
    readonly property color subtext0: "#9aa5ce"
    readonly property color subtext1: "#a9b1d6"
    readonly property color text:     "#c0caf5"
    readonly property color red:      "#f7768e"
    readonly property color maroon:   "#db4b4b"
    readonly property color peach:    "#ff9e64"
    readonly property color yellow:   "#e0af68"
    readonly property color green:    "#9ece6a"
    readonly property color teal:     "#73daca"
    readonly property color sky:      "#7dcfff"
    readonly property color sapphire: "#2ac3de"
    readonly property color blue:     "#7aa2f7"
    readonly property color lavender: "#9d7cd8"
    readonly property color mauve:    "#bb9af7"
    readonly property color pink:     "#ff007c"
}
