# ${THEME_LABEL} — generated by scripts/theme.sh. Do not edit.
# theme.py does `from theme_colors import *` and maps these onto qutebrowser
# settings; only the hexes live here.

ROSEWATER = "#${ROSEWATER}"
FLAMINGO = "#${FLAMINGO}"
PINK = "#${PINK}"
MAUVE = "#${MAUVE}"
RED = "#${RED}"
MAROON = "#${MAROON}"
PEACH = "#${PEACH}"
YELLOW = "#${YELLOW}"
GREEN = "#${GREEN}"
TEAL = "#${TEAL}"
SKY = "#${SKY}"
SAPPHIRE = "#${SAPPHIRE}"
BLUE = "#${BLUE}"
LAVENDER = "#${LAVENDER}"

TEXT = "#${TEXT}"
SUBTEXT1 = "#${SUBTEXT1}"
SUBTEXT0 = "#${SUBTEXT0}"
OVERLAY2 = "#${OVERLAY2}"
OVERLAY1 = "#${OVERLAY1}"
OVERLAY0 = "#${OVERLAY0}"
SURFACE2 = "#${SURFACE2}"
SURFACE1 = "#${SURFACE1}"
SURFACE0 = "#${SURFACE0}"
BASE = "#${BASE}"
MANTLE = "#${MANTLE}"
CRUST = "#${CRUST}"

ACCENT = "#${ACCENT}"
