services:
  ollama:
    image: docker.io/ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /home/nova/Docker/docker_data/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  ollama: {}


