services:
  ollama:
    volumes:
      - /home/nova/Docker/docker_data/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - 11434:11434
    environment:
      DISPLAY: $DISPLAY
      PATH: $PATH
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities: [gpu]

