-- ${THEME_LABEL} — generated by scripts/theme.sh. Do not edit.
-- Consumed by lua/plugins/colorscheme.lua.
--
-- ponytail: every theme is rendered through the catppuccin plugin's
-- color_overrides table rather than installing one nvim plugin per theme.
-- Catppuccin accepts overrides for all 26 palette slots, so a full repaint is
-- possible without touching lazy-lock.json. Swap to a dedicated plugin only if
-- a theme needs different highlight-group semantics, not just different hexes.
return {
	name = "${THEME_NAME}",
	label = "${THEME_LABEL}",
	polarity = "${THEME_POLARITY}",
	palette = {
		rosewater = "#${ROSEWATER}",
		flamingo = "#${FLAMINGO}",
		pink = "#${PINK}",
		mauve = "#${MAUVE}",
		red = "#${RED}",
		maroon = "#${MAROON}",
		peach = "#${PEACH}",
		yellow = "#${YELLOW}",
		green = "#${GREEN}",
		teal = "#${TEAL}",
		sky = "#${SKY}",
		sapphire = "#${SAPPHIRE}",
		blue = "#${BLUE}",
		lavender = "#${LAVENDER}",
		text = "#${TEXT}",
		subtext1 = "#${SUBTEXT1}",
		subtext0 = "#${SUBTEXT0}",
		overlay2 = "#${OVERLAY2}",
		overlay1 = "#${OVERLAY1}",
		overlay0 = "#${OVERLAY0}",
		surface2 = "#${SURFACE2}",
		surface1 = "#${SURFACE1}",
		surface0 = "#${SURFACE0}",
		base = "#${BASE}",
		mantle = "#${MANTLE}",
		crust = "#${CRUST}",
	},
	accent = "#${ACCENT}",
}
