# Tokyo Night — generated by scripts/theme.sh. Do not edit.
# Sourced by .zshrc before prompt.zsh.

POWERLINE_COLOR_USER_FG="%F{#bb9af7}"
POWERLINE_COLOR_PATH_FG="%F{#7dcfff}"
POWERLINE_COLOR_GIT_FG="%F{#9ece6a}"
POWERLINE_COLOR_GIT_DIRTY_FG="%F{#f7768e}"
POWERLINE_COLOR_TIME_FG="%F{#565f89}"
POWERLINE_COLOR_STATUS_FG="%F{#73daca}"
POWERLINE_COLOR_ERROR_FG="%F{#db4b4b}"
POWERLINE_COLOR_SEPARATOR_FG="%F{#292e42}"

export FZF_DEFAULT_OPTS="\
--color=bg+:#24283b,bg:#1a1b26,spinner:#ffc7c7,hl:#f7768e \
--color=fg:#c0caf5,header:#f7768e,info:#bb9af7,pointer:#ffc7c7 \
--color=marker:#9d7cd8,fg+:#c0caf5,prompt:#bb9af7,hl+:#f7768e \
--color=selected-bg:#292e42 \
--color=border:#414868,label:#c0caf5"
