-- ${THEME_LABEL} — generated by scripts/theme.sh. Do not edit.
-- Same colours as niri's focus ring (modules/colors.kdl).
hl.config({
    general = {
        col = {
            active_border   = { colors = { "rgb(${RING_FROM})", "rgb(${RING_TO})" }, angle = ${RING_ANGLE} },
            inactive_border = "rgb(${RING_INACTIVE})",
        },
    },
})
