# Tokyo Night — generated by scripts/theme.sh. Do not edit.
# theme.py does `from theme_colors import *` and maps these onto qutebrowser
# settings; only the hexes live here.

ROSEWATER = "#ffc7c7"
FLAMINGO = "#ff9e64"
PINK = "#ff007c"
MAUVE = "#bb9af7"
RED = "#f7768e"
MAROON = "#db4b4b"
PEACH = "#ff9e64"
YELLOW = "#e0af68"
GREEN = "#9ece6a"
TEAL = "#73daca"
SKY = "#7dcfff"
SAPPHIRE = "#2ac3de"
BLUE = "#7aa2f7"
LAVENDER = "#9d7cd8"

TEXT = "#c0caf5"
SUBTEXT1 = "#a9b1d6"
SUBTEXT0 = "#9aa5ce"
OVERLAY2 = "#737aa2"
OVERLAY1 = "#565f89"
OVERLAY0 = "#414868"
SURFACE2 = "#3b4261"
SURFACE1 = "#292e42"
SURFACE0 = "#24283b"
BASE = "#1a1b26"
MANTLE = "#16161e"
CRUST = "#0c0e14"

ACCENT = "#bb9af7"
