-- Tokyo Night — generated by scripts/theme.sh. Do not edit.
-- Consumed by lua/plugins/colorscheme.lua.
--
-- ponytail: every theme is rendered through the catppuccin plugin's
-- color_overrides table rather than installing one nvim plugin per theme.
-- Catppuccin accepts overrides for all 26 palette slots, so a full repaint is
-- possible without touching lazy-lock.json. Swap to a dedicated plugin only if
-- a theme needs different highlight-group semantics, not just different hexes.
return {
	name = "tokyonight",
	label = "Tokyo Night",
	polarity = "dark",
	palette = {
		rosewater = "#ffc7c7",
		flamingo = "#ff9e64",
		pink = "#ff007c",
		mauve = "#bb9af7",
		red = "#f7768e",
		maroon = "#db4b4b",
		peach = "#ff9e64",
		yellow = "#e0af68",
		green = "#9ece6a",
		teal = "#73daca",
		sky = "#7dcfff",
		sapphire = "#2ac3de",
		blue = "#7aa2f7",
		lavender = "#9d7cd8",
		text = "#c0caf5",
		subtext1 = "#a9b1d6",
		subtext0 = "#9aa5ce",
		overlay2 = "#737aa2",
		overlay1 = "#565f89",
		overlay0 = "#414868",
		surface2 = "#3b4261",
		surface1 = "#292e42",
		surface0 = "#24283b",
		base = "#1a1b26",
		mantle = "#16161e",
		crust = "#0c0e14",
	},
	accent = "#bb9af7",
}
