# ${THEME_LABEL} — generated by scripts/theme.sh. Do not edit.
# Sourced by .zshrc before prompt.zsh.

POWERLINE_COLOR_USER_FG="%F{#${ACCENT}}"
POWERLINE_COLOR_PATH_FG="%F{#${SKY}}"
POWERLINE_COLOR_GIT_FG="%F{#${GREEN}}"
POWERLINE_COLOR_GIT_DIRTY_FG="%F{#${RED}}"
POWERLINE_COLOR_TIME_FG="%F{#${OVERLAY1}}"
POWERLINE_COLOR_STATUS_FG="%F{#${TEAL}}"
POWERLINE_COLOR_ERROR_FG="%F{#${MAROON}}"
POWERLINE_COLOR_SEPARATOR_FG="%F{#${SURFACE1}}"

export FZF_DEFAULT_OPTS="\
--color=bg+:#${SURFACE0},bg:#${BASE},spinner:#${ROSEWATER},hl:#${RED} \
--color=fg:#${TEXT},header:#${RED},info:#${ACCENT},pointer:#${ROSEWATER} \
--color=marker:#${LAVENDER},fg+:#${TEXT},prompt:#${ACCENT},hl+:#${RED} \
--color=selected-bg:#${SURFACE1} \
--color=border:#${OVERLAY0},label:#${TEXT}"
