# ${THEME_LABEL} — generated by scripts/theme.sh. Do not edit.
set -gx FZF_DEFAULT_OPTS "\
--color=bg+:#${SURFACE0},bg:#${BASE},spinner:#${ROSEWATER},hl:#${RED} \
--color=fg:#${TEXT},header:#${RED},info:#${ACCENT},pointer:#${ROSEWATER} \
--color=marker:#${LAVENDER},fg+:#${TEXT},prompt:#${ACCENT},hl+:#${RED} \
--color=selected-bg:#${SURFACE1} \
--color=border:#${OVERLAY0},label:#${TEXT}"
