# Tokyo Night — generated by scripts/theme.sh. Do not edit.
set -gx FZF_DEFAULT_OPTS "\
--color=bg+:#24283b,bg:#1a1b26,spinner:#ffc7c7,hl:#f7768e \
--color=fg:#c0caf5,header:#f7768e,info:#bb9af7,pointer:#ffc7c7 \
--color=marker:#9d7cd8,fg+:#c0caf5,prompt:#bb9af7,hl+:#f7768e \
--color=selected-bg:#292e42 \
--color=border:#414868,label:#c0caf5"
