# Autostart Applications #
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk
exec-once = wl-paste -t text --watch clipman store &
exec-once = valent --gapplication-service &
exec-once = wpaperd -d &
exec-once = fcitx5 -d &
exec-once = nm-applet --indicator &
exec-once = blueman-applet &
exec-once = systemctl --user start hyprpolkitagent
exec-once = systemctl --user start xdg-desktop-portal-hyprland
exec-once = systemctl --user start xdg-desktop-portal
exec-once = systemctl --user start xdg-desktop-portal-gtk
exec-once = hypridle &
exec-once = udiskie &
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = waybar &
exec-once = swaync &
