#!/usr/bin/env bash
# Lock with swaylock-effects, using the CURRENT wallpaper as the background.
# swaylock's own `screenshots` option would show whatever is on screen, i.e.
# your open windows; DMS rotates the wallpaper, so ask it rather than hardcode.
# ponytail: falls back to the flat `color=` in swaylock/config (generated by
# scripts/theme.sh) if dms is not answering.

# Island owns the wallpaper under Hyprland, DMS under niri.
wallpaper=$(qs -c island ipc call island getWallpaper 2>/dev/null || dms ipc call wallpaper get 2>/dev/null)

if [ -f "$wallpaper" ]; then
    exec swaylock -i "$wallpaper"
else
    exec swaylock
fi
