#!/usr/bin/env bash
# Run a site as a standalone "web app": no tabs, no statusbar, own window, own
# app_id so niri can place it.
#
#   qute-webapp.sh whatsapp https://web.whatsapp.com
#   qute-webapp.sh --desktop whatsapp https://web.whatsapp.com   # + .desktop entry
#
# Each app gets its own basedir under ~/.local/share/qutebrowser-apps/<name>,
# which means its own cookie jar: you log in once, per app. That isolation is
# the point - the app cannot see your main session, and vice versa.
#
# The app's config execs the main config.py, so theme, adblock, dark mode,
# HTTPS-only and permissions all carry over. Only the chrome is stripped.
set -euo pipefail

MAIN_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/qutebrowser"
APPS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/qutebrowser-apps"

make_desktop=0
if [[ ${1:-} == "--desktop" ]]; then
	make_desktop=1
	shift
fi

name=${1:-}
url=${2:-}
if [[ -z $name || -z $url ]]; then
	echo "usage: $(basename "$0") [--desktop] <name> <url>" >&2
	exit 1
fi

basedir="$APPS_DIR/$name"
app_id="qutebrowser-$name"
mkdir -p "$basedir/config"

# Excludes are read via config.configdir, which points at the app basedir, so
# link them through to the main ones instead of maintaining a second copy.
for f in darkmode_excludes https_excludes; do
	[[ -e "$MAIN_CONFIG/$f" ]] && ln -sfn "$MAIN_CONFIG/$f" "$basedir/config/$f"
done

cat > "$basedir/config/config.py" <<EOF
# Generated by qute-webapp.sh - edit the main config instead.
import os
import sys

MAIN = os.path.expanduser("$MAIN_CONFIG")
sys.path.insert(0, MAIN)  # so the theme/https_only modules import
_main_cfg = os.path.join(MAIN, "config.py")
exec(compile(open(_main_cfg).read(), _main_cfg, "exec"))

# --- web app chrome ---------------------------------------------------------
c.tabs.show = "multiple"      # hidden until the app opens a second tab
c.statusbar.show = "in-mode"  # only while typing a command
c.scrolling.bar = "never"
c.window.title_format = "$name"
c.url.start_pages = ["$url"]
c.url.default_page = "$url"
EOF

if ((make_desktop)); then
	apps="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
	mkdir -p "$apps"
	cat > "$apps/$app_id.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=${name^}
Exec=$(readlink -f "$0") $name $url
Icon=qutebrowser
StartupWMClass=$app_id
Categories=Network;
EOF
	echo "wrote $apps/$app_id.desktop"
fi

exec qutebrowser \
	--basedir "$basedir" \
	--desktop-file-name "$app_id" \
	--target window \
	"$url"
