;;; theme.el --- ${THEME_LABEL} -*- lexical-binding: t; -*-
;; Generated by scripts/theme.sh. Do not edit. Loaded by init.el.
;;
;; ponytail: every theme is painted through catppuccin-theme's palette slots,
;; the same trick as nvim/lua/theme.lua, instead of one Emacs package per theme.
;; The palette is set before the theme file first loads (catppuccin keeps an
;; already-set value), so the theme is loaded exactly once.

(setq catppuccin-flavor 'mocha
      catppuccin-mocha-colors
      '((rosewater . "#${ROSEWATER}")
        (flamingo  . "#${FLAMINGO}")
        (pink      . "#${PINK}")
        (mauve     . "#${MAUVE}")
        (red       . "#${RED}")
        (maroon    . "#${MAROON}")
        (peach     . "#${PEACH}")
        (yellow    . "#${YELLOW}")
        (green     . "#${GREEN}")
        (teal      . "#${TEAL}")
        (sky       . "#${SKY}")
        (sapphire  . "#${SAPPHIRE}")
        (blue      . "#${BLUE}")
        (lavender  . "#${LAVENDER}")
        (text      . "#${TEXT}")
        (subtext1  . "#${SUBTEXT1}")
        (subtext0  . "#${SUBTEXT0}")
        (overlay2  . "#${OVERLAY2}")
        (overlay1  . "#${OVERLAY1}")
        (overlay0  . "#${OVERLAY0}")
        (surface2  . "#${SURFACE2}")
        (surface1  . "#${SURFACE1}")
        (surface0  . "#${SURFACE0}")
        (base      . "#${BASE}")
        (mantle    . "#${MANTLE}")
        (crust     . "#${CRUST}")))

(load-theme 'catppuccin t)
