services:
  ollama:
    volumes:
      - /home/nova/Docker/docker_data/ollama:/root/.ollama
    container_name: ollama
    tty: true
    image: docker.io/ollama/ollama 
    ports:
      - "11434:11434"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: "no"

volumes:
  ollama: {}
