//@ pragma UseQApplication
// Theme picker — Quickshell. Bound to Mod+Shift+T. Resident daemon, toggled over IPC.
//
// Rows come from `scripts/theme.sh --list`, one tab-separated line per palette
// in system/themes/palettes/. Enter runs `scripts/theme.sh <name>`, which
// re-renders every templated config. No search box: there are a handful of
// themes and the list is always fully visible.
import Quickshell
import Quickshell.Wayland
import Quickshell.Io
import QtQuick
import common
import QtQuick.Controls
import QtQuick.Layouts

ShellRoot {
    id: root
    readonly property string themeScript: Quickshell.env("HOME") + "/.dotfiles/scripts/theme.sh"

    // Palette: common/Colors.qml, generated by scripts/theme.sh.
    readonly property color bg:      Colors.bg
    readonly property color inputBg: Colors.inputBg
    readonly property color outline: Colors.outline
    readonly property color accent:  Colors.accent
    readonly property color selBg:   Colors.selBg
    readonly property color fg:      Colors.fg
    readonly property color subtext: Colors.subtext
    readonly property string uiFont: "JetBrainsMono Nerd Font"

    property int sel: 0
    property var rows: []            // [{name,label,desc,accent,base}]
    property string current: ""
    property bool applying: false

    Process {
        id: lister
        command: ["bash", themeScript, "--list"]
        stdout: StdioCollector {
            onStreamFinished: {
                var out = [];
                var lines = text.split("\n");
                for (var i = 0; i < lines.length; i++) {
                    if (lines[i].trim() === "") continue;
                    var f = lines[i].split("\t");
                    out.push({ name: f[0], label: f[1], desc: f[2], accent: f[3], base: f[4] });
                }
                rows = out;
                for (var j = 0; j < rows.length; j++)
                    if (rows[j].name === current) sel = j;
            }
        }
    }

    Process {
        id: reader
        command: ["bash", themeScript, "--current"]
        stdout: StdioCollector { onStreamFinished: { current = text.trim(); lister.running = true; } }
    }

    Process {
        id: applier
        onExited: { applying = false; reader.running = true; }
    }

    function reload() { reader.running = true; }
    function apply(row) {
        if (!row || applying) return;
        applying = true;
        applier.command = ["bash", themeScript, row.name];
        applier.running = true;
        win.visible = false;
    }

    IpcHandler {
        target: "theme"
        function toggle(): void {
            if (win.visible) { win.visible = false; return; }
            reload();
            win.visible = true;
        }
    }

    PanelWindow {
        id: win
        visible: false
        anchors { top: false; bottom: false; left: false; right: false }
        implicitWidth: 620
        implicitHeight: 92 + Math.max(1, rows.length) * 64
        color: "transparent"
        WlrLayershell.layer: WlrLayer.Overlay
        WlrLayershell.keyboardFocus: WlrKeyboardFocus.Exclusive
        WlrLayershell.namespace: "quickshell-theme"

        // ponytail: open-only expand-from-centre; close hides instantly
        property real anim: 0
        Behavior on anim { NumberAnimation { duration: 150; easing.type: Easing.OutCubic } }
        onVisibleChanged: { anim = visible ? 1 : 0; if (visible) Qt.callLater(function () { keys.forceActiveFocus(); }) }

        Rectangle {
            anchors.fill: parent
            transform: Scale { origin.y: win.height / 2; yScale: win.anim }
            radius: 4
            color: bg
            border.color: outline
            border.width: 1

            FocusScope {
                id: keys
                anchors.fill: parent
                focus: true
                Keys.onPressed: (e) => {
                    if (e.key === Qt.Key_Escape) { win.visible = false; e.accepted = true; }
                    else if (e.key === Qt.Key_Down || e.key === Qt.Key_J || e.key === Qt.Key_Tab) {
                        if (rows.length) sel = (sel + 1) % rows.length; e.accepted = true;
                    } else if (e.key === Qt.Key_Up || e.key === Qt.Key_K || e.key === Qt.Key_Backtab) {
                        if (rows.length) sel = (sel - 1 + rows.length) % rows.length; e.accepted = true;
                    } else if (e.key === Qt.Key_Return || e.key === Qt.Key_Enter) {
                        apply(rows.length ? rows[sel] : null); e.accepted = true;
                    }
                }

                ColumnLayout {
                    anchors.fill: parent
                    anchors.margins: 14
                    spacing: 10

                    Rectangle {
                        Layout.fillWidth: true; implicitHeight: 48; radius: 0
                        color: inputBg; border.color: accent; border.width: 1
                        RowLayout {
                            anchors.fill: parent; anchors.leftMargin: 14; anchors.rightMargin: 14; spacing: 10
                            Text { text: "󰏘"; color: accent; font.family: uiFont; font.pixelSize: 18 }
                            Text {
                                Layout.fillWidth: true
                                text: "Theme"; color: fg; font.family: uiFont; font.pixelSize: 16
                            }
                            Text {
                                text: current === "" ? "" : "current: " + current
                                color: subtext; font.family: uiFont; font.pixelSize: 13
                            }
                        }
                    }

                    ListView {
                        id: list
                        Layout.fillWidth: true; Layout.fillHeight: true; clip: true
                        boundsBehavior: Flickable.StopAtBounds
                        ScrollBar.vertical: ScrollBar { }
                        model: rows
                        currentIndex: sel
                        onCurrentIndexChanged: positionViewAtIndex(currentIndex, ListView.Contain)
                        delegate: Rectangle {
                            required property int index
                            required property var modelData
                            width: ListView.view.width; height: 64; radius: 0
                            color: index === sel ? selBg : "transparent"
                            RowLayout {
                                anchors.fill: parent; anchors.leftMargin: 14; anchors.rightMargin: 14; spacing: 14

                                // Swatch: the theme's background with its accent inside.
                                Rectangle {
                                    Layout.preferredWidth: 34; Layout.preferredHeight: 34
                                    radius: 17
                                    color: modelData.base
                                    border.color: outline; border.width: 1
                                    Rectangle {
                                        anchors.centerIn: parent
                                        width: 16; height: 16; radius: 8
                                        color: modelData.accent
                                    }
                                }

                                ColumnLayout {
                                    Layout.fillWidth: true; spacing: 0
                                    Text {
                                        text: modelData.label; color: fg
                                        font.family: uiFont; font.pixelSize: 15
                                        elide: Text.ElideRight; Layout.fillWidth: true
                                    }
                                    Text {
                                        text: modelData.desc
                                        color: index === sel ? fg : subtext
                                        font.family: uiFont; font.pixelSize: 12
                                        elide: Text.ElideRight; Layout.fillWidth: true
                                    }
                                }

                                // Marks the active theme. Hovering a row moves the
                                // keyboard selection, as in the other menus, so the
                                // check mark is the only stable "you are here".
                                Text {
                                    text: modelData.name === current ? "\u2713" : ""
                                    color: accent; font.family: uiFont; font.pixelSize: 18
                                }
                            }
                            MouseArea {
                                anchors.fill: parent; hoverEnabled: true
                                onEntered: sel = index
                                onClicked: apply(modelData)
                            }
                        }
                    }
                }
            }
        }
    }
}
